In [2]:
# Import libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

Problem Statement

The objective of this project is to analyze Delhi's climate data and identify trends in temperature, humidity, wind speed, and atmospheric pressure over time.

The analysis aims to:

Understand weather patterns in Delhi.
Identify seasonal variations.
Detect anomalies and outliers.
Examine relationships among climate variables.
Generate meaningful insights through visualization

# Data Collection

In [8]:
# Load datasets

train_df = pd.read_csv("DailyDelhiClimateTrain.csv")
test_df = pd.read_csv("DailyDelhiClimateTest.csv")

In [10]:
# View datasets

print(train_df.head())

print(test_df.head())

         date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000
         date   meantemp   humidity  wind_speed  meanpressure
0  2017-01-01  15.913043  85.869565    2.743478     59.000000
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778
2  2017-01-03  17.111111  81.888889    4.016667   1018.333333
3  2017-01-04  18.700000  70.050000    4.545000   1015.700000
4  2017-01-05  18.388889  74.944444    3.300000   1014.333333

In [12]:
# Merge train and test data

df = pd.concat([train_df, test_df], ignore_index=True)

df.head()

         date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000

In [16]:
# Check dataset 

df.shape
print("Shape of Dataset")
print(df.shape)

print("\n")

print("Number of Rows :", df.shape[0])

print("Number of Columns :", df.shape[1])

print("\n")

print("Column Names")

print(df.columns.tolist())

print("\n")

print("Data Types")

print(df.dtypes)

print("\n")

print("First Five Rows")

display(df.head())

print("\n")

print("Dataset Information")

df.info()

Shape of Dataset
(1576, 5)


Number of Rows : 1576
Number of Columns : 5


Column Names
['date', 'meantemp', 'humidity', 'wind_speed', 'meanpressure']


Data Types
date             object
meantemp        float64
humidity        float64
wind_speed      float64
meanpressure    float64
dtype: object


First Five Rows

         date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1576 entries, 0 to 1575
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1576 non-null   object
 1   meantemp      1576 non-null   float64
 2   humidity      1576 non-null   float64
 3   wind_speed    1576 non-null   float64
 4   meanpressure  1576 non-null   float64
dtypes: float64(4), object(1)
memory usage: 61.7+ KB

# Data Cleaning

In [25]:
# Dataset information
df.info()

# Missing values
df.isnull().sum()

# Duplicate values
df.duplicated().sum()

# Remove duplicates
df = df.drop_duplicates()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1576 entries, 0 to 1575
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1576 non-null   object
 1   meantemp      1576 non-null   float64
 2   humidity      1576 non-null   float64
 3   wind_speed    1576 non-null   float64
 4   meanpressure  1576 non-null   float64
dtypes: float64(4), object(1)
memory usage: 61.7+ KB